### ISSUE TITLE
[Bug] run_correction.py 和 run_meta_feedback.py 函数调用名称错误

### ISSUE THREAD

**Issue by WencWu** [open-compass/CriticEval#2]
1. run_correction.py
```python
# line 131
fast_mode=fast_mode,  # fast_mode 变量未传入，导致变量未定义错误
```
```python
# line 169
evaluate_obj  # 函数名应改为 evaluate_correction_obj
...
# line 177
evaluate_sub  # 函数名应改为 evaluate_correction_sub
```
2. run_meta_feedback.py
```python
# line 81
evaluate_obj  # 函数名应改为 evaluate_meta_feedback_obj
```

**Comment by gmftbyGMFTBY** [comment]
Thank you very much for your reminder. Due to version control issues, some problems were not synchronized. We have updated the code based on your feedback. 

If you have any problem, please feel free to contact me with my WeChat @gmftby！I am hoping to solve your issues and exchange experiences with you

**Comment by WencWu** [comment]
> Thank you very much for your reminder. Due to version control issues, some problems were not synchronized. We have updated the code based on your feedback.
> 
> If you have any problem, please feel free to contact me with my WeChat @GMFTBY！I am hoping to solve your issues and exchange experiences with you

Thanks. I have added you on WeChat. I still have some questions about aligning indicators and would like to consult you.
